# Generated by Django 2.0.3 on 2018-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
