# Generated by Django 2.0.3 on 2018-03-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date_added', models.DateTimeField()),
                ('price_offered', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Artiste')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Retailer')),
            ],
        ),
    ]
