# Generated by Django 2.0.3 on 2018-03-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_offered',
            new_name='price',
        ),
    ]
