# Generated by Django 2.0.3 on 2018-03-21 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180321_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 18, 51, 16, 513032, tzinfo=utc)),
        ),
    ]
