# Generated by Django 2.0.3 on 2018-03-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180326_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artiste',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retailer',
        ),
    ]
